config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'

  resources :scripts
  resources :comments
  devise_for :users
  get 'tags/:tag', to: 'links#index', as: :tag
  resources :profiles
  resources :links do
    member do
      put "like",    to: "links#upvote"
      put "dislike", to: "links#downvote"
    end
    resources :comments
  end

  root "pages#home"
  get 'profiles/:id' => 'profiles#show'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :link
end

app/models/link.rb
####This section is our script model. The validates_attachment_content_type is for PAPERCLIP

class Link < ActiveRecord::Base
	acts_as_votable
  acts_as_taggable
	belongs_to :user
	has_many :comments, dependent: :destroy
    has_attached_file :image, :styles => { :medium => "400x500>"}
    validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif", "application/pdf"]
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  acts_as_taggable
  belongs_to :user
  has_attached_file :profile_image, :styles => { :medium => "300x300>", :thumb => "60x60>" }
      validates_attachment_content_type :profile_image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :links, dependent: :destroy
  has_many :scripts

  has_one :profile, dependent: :destroy
  after_create :create_profile

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]


  def create
    @link = Link.find(params[:link_id])
    @comment = @link.comments.new(comment_params)
    @comment.user = current_user

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @link, notice: 'Comment was successfully created.' }
        format.json { render json: @comment, status: :created, location: @comment }
      else
        format.html { render action: "new" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:link_id, :body, :user_id)
    end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show, :edit, :update, :destroy]
  before_action :link_params, only: [:create]
  before_filter :authenticate_user!, except: [:index, :show]

  require 'open-uri'

  # GET /links
  # GET /links.json
  def index
    if params[:tag]
       @links = Link.tagged_with(params[:tag])
     else
       @links = Link.all.sort{|x, y| y.votes_for.size <=> x.votes_for.size }
    end
  end

  # GET /links/1
  # GET /links/1.json
  def show
    @link = Link.find(params[:id])
  end

  # GET /links/new
  def new
    @link = current_user.links.build
  end

  # GET /links/1/edit
  def edit

  end

  # POST /links
  # POST /links.json
  def create
    @link = current_user.links.build(link_params)


    respond_to do |format|
      if @link.save
        format.html { redirect_to @link, notice: 'Link was successfully created.' }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /links/1
  # PATCH/PUT /links/1.json
  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to @link, notice: 'Link was successfully updated.' }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    @link.destroy
    respond_to do |format|
      format.html { redirect_to links_url, notice: 'Link was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def upvote
    @link = Link.find(params[:id])
    @link.upvote_by current_user
    redirect_to :back
  end

  def downvote
    @link = Link.find(params[:id])
    @link.downvote_by current_user
    redirect_to :back
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def link_params
      params.require(:link).permit(:title, :url, :description, :image, :written_by, :plot_description, :estimated_budget, :tag_list)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def main
  end
  
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]
  before_action :profile_params, only: [:create]
  # :show,

  def index
        @profiles = Profile.all
    if params[:tag]
       @profiles = Profile.tagged_with(params[:tag])
     else
       @profiles = Profile.all
    end
  end

  def show
  end

  def new
    @profile = Profile.new
  end

  def edit
  end

  def create
    @profile = Profile.new(profile_params)
    @profile.save
  end

  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Link was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @profile.destroy
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:first_name, :last_name, :gender, :profile_image, :birthdate, :occupation, :city, :comedy, :adventure, :drama, :action, :thriller, :horror, :romantic_comedy, :musical, :documentary, :tag_list)
    end

    #default set of params for the empty profile before being filled.
    # def default_params
    #   defaults = {:first_name => "John", :last_name => "Doe", :gender => "Male", :profile_image => "http://allenbukoff.com/newwavepsychology/JohnDoeMasthead.jpg", :birthdate => "01/01/1950". :occupation => "Writer", :city => "City of Dreams", :comedy => "true", :adventure => "false", :drama => "false", :action => "false", :thriller => "true", :horror => "true", :romantic_comedy => "true", :musical => "false", :documentary => "false"}
    # end

end

app/helpers/application_helper.rb
module ApplicationHelper

    #Return the gravatar in user
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(:email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/links_helper.rb
module LinksHelper

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/scripts_helper.rb
module ScriptsHelper
end

app/views/comments/_comment.html.erb
<!-- This code block is for the comment section in the Script Show -->
<!-- This code block is for the comment section in the Script Show -->


<%= div_for(comment) do %>
	<div class="comments_wrapper clearfix">
		<div class="pull-left">
			<p class="lead"><%= comment.body %></p>
			<p><small>Submitted <strong><%= time_ago_in_words(comment.created_at) %> ago</strong> by <%= comment.user.email %></small></p>
		</div>

<!-- Notice the if comment.user == current.user. This allows only ONE person to destroy -->
		<div class="btn-group pull-right">
			<% if comment.user == current_user %>
				<%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-default" %>
			<% end %>
		</div>
	</div>
<% end %>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :link_id %><br>
    <%= f.number_field :link_id %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<% if user_signed_in? %>

<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Link</th>
      <th>Body</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.link_id %></td>
        <td><%= comment.body %></td>
        <td><%= comment.user %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>
<% end %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<% if user_signed_in? -%>

<p id="notice"><%= notice %></p>

<p>
  <strong>Link:</strong>
  <%= @comment.link_id %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>
<% end - %>

app/views/layouts/_header.html.erb
<!--This section represents our NAVBAR/HEADER used throughout our application -->


 <header class="navbar navbar-inverse" role="navigation">
    <div class="navbar-inner">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
  </div>


      <div class="container">
        <div id="logo" class="navbar-brand" class="navbar-brand" href="#"><%= link_to "Script Rocket", root_path %></div>

        <nav class="collapse navbar-collapse navbar-ex1-collapse">
          <% if current_user %>
            <ul class="nav navbar-nav navbar-right">
              <li><%= link_to 'Script List', links_path %></li>
              <li><%= link_to 'Submit Script', new_link_path %></li>
              <% if current_user.profile.first_name == nil %>
                   <li><%= link_to 'Profile', edit_profile_path(current_user.profile) %></li>
              <% else %>
                 <li><%= link_to 'Profile', profile_path(current_user.profile) %></li>
              <% end %>
              <li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
            </ul>
          <% else %>
            <ul class="nav navbar-nav pull-right">
              <li><%= link_to 'Sign up', new_user_registration_path %></li>
              <li><%= link_to 'Sign in', new_user_session_path %></li>
            </ul>
          <% end %>
        </nav>
      </div>
    </div>
  </header>


<!--If you'd like to enable flash messages, Uncomment the section below -->


<!--   <div id="main_content" class="container">
            <%#flash.each do |name, msg| %>
            <%#=content_tag(:div, msg, class: "alert alert-info") %>
            <%# end %>
          </div> -->

app/views/layouts/application.html.erb
<!-- This section contains our application scripts  -->

<!DOCTYPE html>
<html>
<head>
  <title>WebbyWood</title>

  <link href='//fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
  <link href='//fonts.googleapis.com/css?family=Lato:400,700,900' rel='stylesheet' type='text/css'>
  <link href='//fonts.googleapis.com/css?family=Raleway:400,800,700,900,300,100' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Slabo+27px">

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>

  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

</head>

<body>
 <%= render 'layouts/header' %>

 <%= yield %>

</body>
</html>

app/views/links/_form.html.erb
<!-- This code block is for the SCRIPT UPLOAD section-->
<!-- The Form groups below are the different fields in our "Panel-body" -->
<div class="overlay">



<!--Code block to help prevent unknown formats upload -->
<%= form_for @link, html: { multipart: true } do |f| %>

  <% if @link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% @link.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<!--This is form where users upload image, name script, etc.. -->
<div class="container">
  <div id="uploadinfoblock">
    <h1>Upload your script</h1>
    <br>
    <h4>Everday people are looking for movie and series ideas to turn into great entertainment. Submit your finished script, mini-series, or concept here today.</h4>
    <img src="https://dl.dropboxusercontent.com/u/27576976/images/slate.png">
    <br>
    <br>
    <h4>Whether it's a drama, action, or even sci-fi, we believe independent content can be created anywhere at anytime.</h4>
  </div>
    <div class="row vertical-offset-100">
      <div class="col-md-4 col-md-offset-4"  id="submitscriptblock">
    <div class="panel panel-primary panel-transparent">
      <div class="panel-heading">
        <h3 class="panel-title">Post Your Script</h3>
        <div class="panel-body">

  <div class="form-group">
    <%= f.label :Cover_Image %>
    <%= f.file_field :image, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :Screenplay_title %><br>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :Written_By %><br>
    <%= f.text_field :written_by, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :Plot_Description %><br>
    <%= f.text_field :plot_description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :Estimated_Budget %><br>
    <%= f.text_field :estimated_budget, class: "form-control" %>
  </div>


  <div class="form-group">
    <%= f.label :Script_URL %><br>
    <%= f.text_field :url, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label(:tag_list, "Tags* (seperated by commas)") %><br />
    <%= f.text_field(:tag_list, value: @link.tag_list.join(","))%>
  </div>


<!-- Submit button that points to BOOTSTRAP Modal-->
<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
  Submit Script
</button>

<!-- Terms and Conditions Modal -->
<div id="onlymodal">
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Terms & Conditions</h4>
      </div>
      <div class="modal-body" id="modalterms">
        <h4>WebbyWood Terms & Conditions</h4>
        <p>All copyright, trademarks, design rights, patents and other intellectual property rights (registered and unregistered) in and on WebbyWood Services are assumed to belong to the User or third parties (which may include you or other users) uploading the desired script.</p>
        <p>While WebbyWood encourages open-source community sharing of creative resources, we highly recommend one register their material under copyright. </p>
        <p>Nothing in the Terms grants you a right or licence to use any trade mark, design right or copyright owned or controlled by WebbyWood or any other third party except as expressly provided in the Terms.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class= "btn btn-lg btn-danger" data-dismiss="modal">Cancel</button>
        <%= f.submit "Submit Script", class: "btn btn-lg btn-primary" %>
      </div>
    </div>
  </div>
</div>


<% end %>
</div>
</div>

app/views/links/edit.html.erb
<!--This is the section for editing -->
<!--Notice it pushes to the "_form.html.erb" -->

<h1>Editing Link</h1>

<%= render 'form' %>


<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

app/views/links/index.html.erb
<!-- This code block is for the MAIN Script list aka the home page -->
<!-- We are currently running into issues with displaying title and functional link (11/5/15 @ 9am ET) -->

<div class="overlay">

<div class="container" id="mainindexbody">
<% @links.each do |link| %>

<!-- PDFreader set up to be used in the rest of the document -->
<% url = open(link.url) %>
<% reader = PDF::Reader.new(url) %>
<!-- Do not remove -->





<div class="link" display="inblock">

<!--THIS SECTION IS FOR PROFILE PICTURE THAT SPINS TO DATA -->
  <ul class="demo-3">
    <li>
        <figure>
              <div id="profilepicmain"><%= image_tag link.user.profile.profile_image.url(:medium) %></div>
            <figcaption>
                <h2><%= link_to (link.user.profile.first_name + " " + link.user.profile.last_name), profile_path(link.user.profile) %></h2>
            </figcaption>
        </figure>
    </li>
</ul>
<!--THIS SECTION IS THE END FOR PROFILE PICTURE THAT SPINS TO DATA -->


<!--THIS SECTION IS FOR THE BODY OF SCRIPT INFO ON THE MAIN PAGE -->
  <div id="coverimage"> <td><%= image_tag link.image.url(:medium) %></td> </div>
  <br>
    <h4><div>Written by</div><%= link.written_by %></h4>
    <h5><div><strong>Plot:</strong><i></div><div id= "plotdescription"><%= link.plot_description %></div></h5></i>
    <h6><div><strong>Estimated Budget:</strong></div><%= link.estimated_budget %></h6>
    <h6><div>Page Count: <%= reader.page_count %></div></h6>
    <div id ="titlebutton"><h2><%= link_to link.title, link %><br></h2></div>
    <h6><small class="author">Submitted <%= time_ago_in_words(link.created_at) %> ago by <%= link.user.email %></small></h6>
    <p>Tags: <%= raw link.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %></p>

   <div class="btn-group">
    <a class="btn btn-default btn-sm" href="<%= link.url %>" target="_blank">
      Read Script
    </a>

    <div class="btn-group" id="voteButtons">
    <%= link_to like_link_path(link), method: :put, class: "btn btn-default btn-sm" do %>
      <span class="glyphicon glyphicon-chevron-up"></span>
        Like
      <%= link.get_upvotes.size %>
    <% end %>
  </div>
  </div>
</div>
  <% end %>
</div>
</div>
<!--THIS SECTION IS THE END FOR THE BODY OF SCRIPT INFO ON THE MAIN PAGE -->

app/views/links/new.html.erb
<!--This is the New script section, it is unseen in our current base and automattically forwards to _form.html.erb in the links folder --> 

<%= render 'form' %>

app/views/links/show.html.erb
<!-- When you click on a script from the homepage, this is the page you are taken too -->
<!-- This section includes headers,script images, upvote/downvote likes -->
<div class="overlay">
<div class="container" id="mainindexbody">

<!-- PDFreader set up to be used in the rest of the document -->
<% url = open(@link.url) %>
<% reader = PDF::Reader.new(url) %>
<!-- Do not remove -->

<!--Script title -->
<div class="page-header">
    <h1><a href="<%= @link.url %>"><%= @link.title %></a><br><br> <small>Submitted by <%= @link.written_by %></small></h1>
    <h4><div>Written by</div><%= @link.written_by %></h4>
    <h5><div><strong>Plot:</strong><i></div><%= @link.plot_description %></h5></i>
    <h6><div><strong>Estimated Budget:</strong></div><%= @link.estimated_budget %></h6>
    <h6><div>Page Count:</div><%= reader.page_count %></h6>
</div>


<!--Script Image -->
<div class="script">
	<%= image_tag @link.image.url(:medium) %>
</div>

<br>

<!--Visit URL button -->
<div class="btn-group">
	<%= link_to 'Read Script', @link.url, class: "btn btn-primary" %>
</div>

<!--If user is the CURRENT user give them the option to edit or destory their post -->
<% if @link.user == current_user -%>
	<div class="btn-group">
		<%= link_to 'Edit Script', edit_link_path(@link), class: "btn btn-default" %>
		<%= link_to 'Delete Script', @link, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default" %>
	</div>
<% end %>

<!--Upvote and Down vote buttons -->
<div class="btn-group pull-right">
	<%= link_to like_link_path(@link), method: :put, class: "btn btn-default btn-sm" do %>
	<span class="glyphicon glyphicon-chevron-up"></span>
	Upvote
	<%= @link.get_upvotes.size %>
	<% end %>
	<%= link_to dislike_link_path(@link), method: :put, class: "btn btn-default btn-sm" do %>
	<span class="glyphicon glyphicon-chevron-down">
		Downvote
		<%= @link.get_downvotes.size %>
		<% end %>
</div>

<!-- This Section represents the TAGS for a script -->
<br><br><br>
  <% @link.tags.any? %>
  <% @link.tags.each do |tag| %>
  <%= link_to tag.name, tag_path(tag) %>
<% end %>
<!-- End of TAGS section -->


<!--This is the comment section where users can commment on the script -->
<h3 class="comments_title">
	<%= @link.comments.count %> Comments
</h3>


<div id="comments">
	<%= render :partial => @link.comments %>
</div>

<% if user_signed_in? -%>
	<%= simple_form_for [@link, Comment.new] do |f| %>
	<div class="field">
		<%= f.text_area :body, class: "form-control" %>
	</div>
	<br>
	<%= f.submit "Add Comment", class: "btn btn-primary" %>
	<% end %>
<% end -%>

<div>

</div>
</div>

<!--End of comment section -->

app/views/pages/home.html.erb
<!--This section represents the MAIN SPLASH PAGE WITH VIDEO BACKGROUND -->

<!--Video Section-->
<div id="signinbody">
<section class="content-section video-section">
  <div class="pattern-overlay">
    <a id="bgndVideo" class="player" data-property="{videoURL:'https://youtu.be/cW2oYvKE_8o',containment:'.video-section', quality:'large', autoPlay:true, mute:true, opacity:1}"></a>
        <div class="row">
          <div class="col-lg-12">
              <div id="mainpagebuttons">
                  <div id="signupmainbtn">
                    <% if user_signed_in? -%>
                      <%= link_to "Read Top Scripts", links_path, class: "btn btn-warning btn-lg" %>
                    <% else %>
                      <%= link_to "Log In", new_user_session_path, class: "btn btn-warning btn-lg" %>
                      <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-success btn-lg" %> 
                    <% end %>
                  </div>
                  <h1>Write. Share. Connect.</h1>
                  <h3>Disrupting Hollywood One Script At A Time</h3>
              </div>

        </div>
      </div>
    </div>
  </section>
</div>
<!--Video Section Ends Here-->

app/views/profiles/edit.html.erb
<%= render 'form' %>

app/views/profiles/new.html.erb
<%= render 'form' %>

app/views/profiles/show.html.erb
  <div class="overlay">
<div class="container">

  <br>
  <br>
  <br>

<div id="tag_cloud">
  
  <% tag_cloud Profile.tag_counts, %w[s m l] do |tag, css_class| %>
    <%= link_to tag.name, tag_path(tag.name), class: css_class %>
  <% end %>
</div>

  <div id="profilepic">
  <%= image_tag @profile.profile_image.url(:medium) %>
  </div>

  <div id="profileInfoBlock">
    <h4><div id="profiletopic">Name:</div><div id="profileanswer"><%= @profile.first_name %> <%= @profile.last_name %></div></h4>
    <h4><div id="profiletopic">Occupation:</div> <div id="profileanswer"><%= @profile.occupation %></h4>
    <h4><div id="profiletopic">Location:</div> <%= @profile.city %></h4>
    <h4><div id="profiletopic">Gender:</div> <%= @profile.gender.capitalize %></h4>
    <h4><div id="profiletopic">Birthdate:</div> <%= @profile.birthdate %></h4>
    <br>
    <br>
    <br>
</div>


<div id="recentUploads">
  <h2>Recent Uploads</h2>
  <% @profile.user.links.each do |link| %>
    <img src="<%= link.image.url %>" >
  <% end %>
</div>


    <div id="favoriteGenresBlock">
      <h1><div id="profiletopic">Favorite Genres</div></h1>
      <br>
      <% @profile.tags.any? %>
      <% @profile.tags.each do |tag| %>
      <%= link_to tag.name, tag_path(tag) %>
      <% end %>
    </div>

    <div id="profileButtons">
    <% if current_user.profile.id.to_i == params[:id].to_i %>
      <%= link_to 'Edit Profile', edit_profile_path %>
      <%= link_to 'Cancel Account?', edit_user_registration_path %>
      <br>
    <% end %>
  </div>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
    </div>
  </div>
</div>
</div>
</div>
<!-- <button type="button" class="btn btn-default">
  <span class="glyphicon glyphicon-heart" aria-hidden="true"></span><span> Edit Profile</span>
</button> -->